name: Build Check
run-name: 'Build Check - PR #${{ github.event.pull_request.number }}'

on:
  pull_request:
    types: [ opened, synchronize, reopened, 'ready_for_review' ]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: build-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Check Build Status
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node via .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm run build

  check:
    name: Check Lint Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node via .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm run check
