name: Deploy Site
run-name: 'Deploy Site - ${{ github.event.release.name }}'

on:
  release:
    types: [ published ]

concurrency:
  group: deploy-site
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  checks:
    name: Run Pre-deployment Checks
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node via .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run check

  build:
    name: Build Production
    needs: checks
    if: success()
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v4
        with:
          node-version: '22'

  deploy:
    name: Deploy Production
    needs: build
    if: success()
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
